import type { Metadata } from 'next';
import Header from '@/app/components/Header';
import Footer from '@/app/components/Footer';

export const metadata: Metadata = {
  title: 'Privacy Policy — SelectedRoom',
  description: 'Learn how SelectedRoom collects, uses, and protects your personal data.',
};

const SECTIONS = [
  {
    title: '1. Data We Collect',
    body: 'We collect information you provide directly (name, email, payment details), data generated by your use of our platform (searches, bookings, preferences), and technical data (IP address, browser type, cookies).',
  },
  {
    title: '2. How We Use Your Data',
    body: 'Your data is used to process bookings, personalise your experience, send booking confirmations and receipts, improve our platform, and comply with legal obligations.',
  },
  {
    title: '3. Payment Data',
    body: 'Payment details are processed by Stripe and are never stored on our servers. We store only the booking amount, currency, and transaction reference.',
  },
  {
    title: '4. Data Sharing',
    body: 'We share your booking details with the relevant partner hotel to fulfil your reservation. We do not sell your personal data to third parties for marketing purposes.',
  },
  {
    title: '5. Cookies',
    body: 'We use essential cookies to operate the platform and optional analytics cookies to understand usage patterns. You can manage cookie preferences in your browser settings.',
  },
  {
    title: '6. Data Retention',
    body: 'We retain your account data for as long as your account is active, or as required by law. You may request deletion of your data at any time.',
  },
  {
    title: '7. Your Rights',
    body: 'Depending on your location, you may have the right to access, correct, delete, or export your personal data. Contact us at privacy@selectedroom.com to exercise your rights.',
  },
  {
    title: '8. Contact',
    body: 'For privacy-related inquiries, email privacy@selectedroom.com or write to our registered address.',
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-gray-50">
        <section className="py-14 px-6 text-center" style={{ background: 'linear-gradient(135deg, #0F2260 0%, #1E3A8A 55%, #2563EB 100%)' }}>
          <p className="text-sm font-semibold tracking-widest uppercase text-brand-gold mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">Privacy Policy</h1>
          <p className="text-white/60 text-sm">Last updated: June 2025</p>
        </section>

        <section className="max-w-3xl mx-auto px-6 py-14 space-y-8">
          {SECTIONS.map(({ title, body }) => (
            <div key={title} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <h2 className="text-base font-bold text-gray-900 mb-3">{title}</h2>
              <p className="text-gray-600 text-sm leading-relaxed">{body}</p>
            </div>
          ))}
        </section>
      </main>
      <Footer />
    </>
  );
}
